Commissions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Gallery/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.Gallery, name='Gallery'),
]

MainPage/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

SiteManager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.image_upload_view, name='SiteManager'),
    path('delete/<int:id>', views.image_delete, name='Delete'),
]

Slothypoo/urls.py
from django.contrib import admin, auth
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('SiteManager/', include('SiteManager.urls')),
    path('Commissions/', include('Commissions.urls')),
    path('Gallery/', include('Gallery.urls')),
    path('TOS/', include('TOS.urls')),
    path('MainPage/', include('MainPage.urls')),
    path('', include('MainPage.urls')),
    path('admin/', admin.site.urls),
    path('J38dkIl9RxnqA/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'MainPage.views.view_404'

TOS/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Commissions/models.py
from django.db import models

# Create your models here.

Gallery/models.py
from django.db import models

# Create your models here.

MainPage/models.py
from django.db import models

# Create your models here.

SiteManager/models.py
from datetime import datetime
from email.policy import default
from random import choices
from django.db import models

TAG_CHOICES = (
    ('select tag', 'Select Tag'),
    ('colored', 'Colored'),
    ('emote', 'Emote'),
    ('bust', 'Bust'),
    ('half-Body', 'Half-body'),
    ('full-Body', 'Full-body'),
)

class Image(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')
    tags = models.CharField(max_length=15, choices = TAG_CHOICES, default = 'Select Tag')
    add_date = models.DateTimeField(auto_now_add=True)
    is_NSFW = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    

TOS/models.py
from django.db import models

# Create your models here.

SiteManager/forms.py
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = Image
        fields = ('name', 'image', 'tags', 'is_NSFW')

Commissions/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse

def index(request):  
    return HttpResponse("Hello, world. You're at the Commissions index.")  

Gallery/views.py
from django.shortcuts import render
from SiteManager.models import Image, TAG_CHOICES

# Create your views here.


def Gallery(request):
    if request.method == 'POST':
        print(request.POST)
        admin_obj = Image.objects.filter(tags=request.POST.get('tags'))
    else:
        admin_obj = Image.objects.all()
    
    tag_obj = TAG_CHOICES
    return render(request, "Gallery.html", {'admin_obj': admin_obj, 'tag_obj': tag_obj})

MainPage/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.http import HttpResponse

def index(request):  
    return render(request, "MainPage.html")

def view_404(request, exception=None):
    # make a redirect to homepage
    # you can use the name of url or just the plain link
    return redirect('index') # or redirect('name-of-index-url')

SiteManager/views.py
from django.shortcuts import render
from django.urls import reverse
from .forms import ImageForm
from django.http import HttpResponseRedirect
from .models import Image
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required
def image_upload_view(request):
    admin_obj = Image.objects.all()
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get the current instance object to display in the template
            img_obj = form.instance
            return render(request, 'SiteManager.html', {'form': form, 'img_obj': img_obj, 'admin_obj': admin_obj,})
    else:
        form = ImageForm()
    return render(request, 'SiteManager.html', {'form': form, 'admin_obj': admin_obj,})

@login_required
def image_delete(request, id): #gonna delete sum stuff
    image = Image.objects.get(id=id)
    image.delete()
    return HttpResponseRedirect(reverse('SiteManager'))

TOS/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse

def index(request):  
    return HttpResponse("Hello, world. You're at the TOS index.")  

Gallery/templates/Gallery.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'Gallery/style.css' %}">
    <title>Gallery</title>
</head>
<body>
    <header>
        <div class="artist-pf">
            <h2 >SlothyPoo's Gallery</h2>
        </div>

        <div class="links">
            <a href="/MainPage">
                <h3 class="header-text"> Information </h3>
            </a>
            <a href="/Commissions">
                <h3 class="header-text"> Commission </h3>
            </a>
            <a href="/TOS">
                <h3 class="header-text"> TOS </h3>
            </a>
        </div>
    </header>

    <div class="content">
        <div class="sidebar">

            <h4 id="filter-select">Gallery Filter</h4>
            <form action="{% url 'Gallery' %}" method="POST">
                {% csrf_token %}
                <select name="tags" id="id_tags">
                    {% for tag in tag_obj %}
                        <option value="{{ tag.0 }}">{{ tag.1 }}</option>
                    {% endfor %}
                        
                </select>
                <br>
                <input type="submit" style="width: 85px;" value="Filter">

            </form>
    
        </div>
        
        <div class="image-wrapper">
            <div class="content-images">
                {% for object in admin_obj reversed %}
                <div class="images" >
                    <!-- Trigger the Modal -->
                    <img class="myImg" id="{{ object.id }}" src="{{ object.image.url }}" alt="{{ object.name }}" onclick="bigger('{{ object.id }}')" style="width: calc(27vw - 20px); min-width: 300px; max-width: 500px;">
                    
                    <!-- The Modal -->
                    <div id="myModal{{ object.id }}" class="modal">
                
                        <!-- The Close Button -->
                        <span class="close" id="close{{ object.id }}">&times;</span>
                
                        <!-- Modal Content (The Image) -->
                        <img class="modal-content resize" id="modal{{ object.id }}">
                
                        <!-- Modal Caption (Image Text) -->
                        <div class="caption" id="caption{{ object.id }}"></div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>

    <footer>
        <li>
            <a href="https://twitter.com/SlothyPooo">
                <img src="https://www.freepnglogos.com/uploads/twitter-logo-png/twitter-logo-vector-png-clipart-1.png" alt="">
            </a>
        </li>
        <li>
            <a href="https://discord.com/invite/CQJ4hna6gF">
                <img src="https://www.freepnglogos.com/uploads/discord-logo-png/discord-icon-flat-style-available-svg-png-eps-10.png" alt="">
            </a>
        </li>
        <li>
            <a href="https://www.instagram.com/slothypyu/?hl=en">
                <img src="https://www.freepnglogos.com/uploads/instagram-icon-png/instagram-icon-color-logo-social-media-new-design-22.png" alt="">
            </a>
        </li>
        <li>
            <a href="https://www.patreon.com/SlothyPoo">
                <img src="https://www.freepnglogos.com/uploads/patreon-logo-png/patreon-logo-red-simple-picture-10.png" alt="">
            </a>
        </li>
        <li>
            <a href="https://www.twitch.tv/slothypoo">
                <img src="https://www.freepnglogos.com/uploads/twitch-logo-symbol-25.png" alt="">
            </a>
        </li>
    </footer>

    
    <script src="{% static 'Gallery/javascript.js' %}"></script>
</body>
</html>

MainPage/templates/MainPage.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'MainPage/style.css' %}">
    <title>Slothypoo</title>
</head>
<body>
    <header>
        <div class="links">
            <a href="/Gallery">
                <h3 class="header-text"> Gallery </h3>
            </a>
            <a href="/Commissions">
                <h3 class="header-text"> Commission </h3>
            </a>
            <a href="/TOS">
                <h3 class="header-text"> TOS </h3>
            </a>
        </div>
    </header>

    <div class="content">
        <div class="artist-name">
            <h1>SlothyPoo</h1>
        </div>
        <div class="artist-title">
            <h2>Freelance Digital Artist</h2>
        </div>
        <div class="divider"></div>
        <div>
            <img src="{% static 'media/SlothyPooPF.jpg' %}" alt="" id="artist-pf">
        </div>
        <div class="contacts">
            <h3>Contact Me Through</h3>
            <li>
                <b><u>Discord:</u></b> SlothyPoo#2818
            </li>
            <li>
                <b><u>Twitter DMs:</u></b> @SlothyPooo
            </li>
            <li id="email">
                <b><u>Gmail:</u></b> Slothbuis@gmail.com
            </li>
        </div>
        <div class="divider"></div>
    </div>

    <footer>
        <a href="https://twitter.com/SlothyPooo">
            <li>
                <img src="https://www.freepnglogos.com/uploads/twitter-logo-png/twitter-logo-vector-png-clipart-1.png" alt="">
            </li>
            </a>
        <a href="https://discord.com/invite/CQJ4hna6gF">
            <li>
                <img src="https://www.freepnglogos.com/uploads/discord-logo-png/discord-icon-flat-style-available-svg-png-eps-10.png" alt="">
            </li>
        </a>
        <a href="https://www.instagram.com/slothypyu/?hl=en">
            <li>
                <img src="https://www.freepnglogos.com/uploads/instagram-icon-png/instagram-icon-color-logo-social-media-new-design-22.png" alt="">
            </li>
        </a>
        <a href="https://www.patreon.com/SlothyPoo">
            <li>
                <img src="https://www.freepnglogos.com/uploads/patreon-logo-png/patreon-logo-red-simple-picture-10.png" alt="">
            </li>
        </a>
        <a href="https://www.twitch.tv/slothypoo">
            <li>
                <img src="https://www.freepnglogos.com/uploads/twitch-logo-symbol-25.png" alt="">
            </li>
        </a>
    </footer>
    
</body>
</html>

SiteManager/templates/SiteManager.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Site Manager</title>
    <link rel="stylesheet"  href="{%  static  'SiteManager/style.css'  %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>

    <header>
      <div class="links">
        <a href="/MainPage">
          <h4 class="header-text"> Information </h4>
        </a>
        <a href="/Gallery">
          <h4 class="header-text"> Gallery </h4>
        </a>
        <a href="/Commissions">
          <h4 class="header-text"> Commission </h4>
        </a>
        <a href="/TOS">
          <h4 class="header-text"> TOS </h4>
        </a>
      </div>
    </header>
    
    <div class="card-wrapper">
      <div class="uploader">
          <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit">Upload</button>
          </form>
      </div>
        {% for object in admin_obj reversed %}
        <div class="card" style="width: 18rem;">
            <img src="{{ object.image.url }}" class="card-img-top" height=auto% width=100%>
            <div class="card-body">
                <h5 class="card-title">{{ object.name }}</h5>
                <p class="card-text">{{ object.tags }}</p>

                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal{{ object.id }}">
                  Delete
                </button>

                <!-- Modal -->
                <div class="modal fade" id="modal{{ object.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Confirm Delete</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <img src="{{ object.image.url }}" alt="" style="width: 100%;">
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <a href="delete/{{ object.id }}">
                          <button type="button" class="btn btn-primary"> Delete </button>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>


            </div>
        </div>
        {% endfor %}
    </div>

    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>
</html>

SiteManager/templates/SiteManager_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Site Manager</title>
  </head>
<body>
  
  <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
      </form>
      
      {% comment %} Following is for display purposes {% endcomment %}
      
      {% if img_obj %}
      <h3>Succesfully uploaded : {{img_obj.name}}</h3>
      <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
      {% endif %}
      
      <div>
        {% for object in admin_obj %}
        <div class="card" style="width: 18rem;">
          <img src="{{ object.image.url }}" class="card-img-top" height=auto% width=100%>
          <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <p class="card-text">stuff</p>
          </div>
        </div>
        {% endfor %}
      </div>
      
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  </body>
</html>